# Generated by Django 4.1.6 on 2023-02-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
        migrations.AlterModelTable(
            name='venta',
            table=None,
        ),
    ]
