# Generated by Django 4.1.6 on 2023-02-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_cliente_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fechavencimiento',
            new_name='fechavencimientogarantia',
        ),
    ]
