# Generated by Django 4.1.5 on 2023-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_asignacion_dispositivo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
